export const zipCodeImpl = (faker, options) => faker.location.zipCode(options);
export const cityImpl = (faker) => faker.location.city();
export const buildingNumberImpl = (faker) => faker.location.buildingNumber();
export const streetImpl = (faker) => faker.location.street();
export const streetAddressImpl = (faker, options) => faker.location.streetAddress(options);
export const secondaryAddressImpl = (faker) => faker.location.secondaryAddress();
export const countyImpl = (faker) => faker.location.county();
export const countryImpl = (faker) => faker.location.country();
export const continentImpl = (faker) => faker.location.continent();
export const countryCodeImpl = (faker, variant) => faker.location.countryCode(variant);
export const stateImpl = (faker, options) => faker.location.state(options);
export const latitudeImpl = (faker, options) => faker.location.latitude(options);
export const longitudeImpl = (faker, options) => faker.location.longitude(options);
export const directionImpl = (faker, options) => faker.location.direction(options);
export const cardinalDirectionImpl = (faker, options) => faker.location.cardinalDirection(options);
export const ordinalDirectionImpl = (faker, options) => faker.location.ordinalDirection(options);
export const nearbyGPSCoordinateImpl = (faker, options) => faker.location.nearbyGPSCoordinate(options);
export const timeZoneImpl = (faker) => faker.location.timeZone();
export const languageImpl = (faker) => faker.location.language();
